<a href="https://colab.research.google.com/github/zun43d/CSE-413/blob/main/Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: **Zunaed Ahmed**\
ID: **2215151019**\
Section: **7A1**\
Course: **Simulation & Modeling LAB**

In [2]:
import numpy as np

# **Q1**: Use numpy to create a 3×3 matrix of random integers between 1 and 50.
 - Run the code twice
 - With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.  
 - Without setting a seed, allowing random values to change each time.  

In [8]:
np.random.seed(10)
matrix_with_seed = np.random.randint(1, 50, size=(3, 3))
print("Matrix with seed:\n", matrix_with_seed)

np.random.seed(None)
matrix_without_seed = np.random.randint(1, 50, size=(3, 3))
print("\nMatrix without seed:\n", matrix_without_seed)

Matrix with seed:
 [[10 37 16]
 [ 1 29 26]
 [30 49 30]]

Matrix without seed:
 [[32  3 29]
 [33 22 15]
 [31  9 23]]


- Observe and explain the differences in outputs.

**1. With a fixed seed**
- The random number will always be same no matter how many times we run the code.
- This is usable when we need to run the code multiple times but want to generate the matrix only once.

**2. Wihtout Seeding**
- If there is no seed, everytime the code will generate a new matrix with random values